# Generated by Django 5.1.7 on 2025-03-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_record_customer_category_record_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
